image: maven:3-openjdk-18-slim

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean package
    - echo "Compile complete."
  artifacts:
    paths:
      - impl/target
  tags:
    - check

deploy-job:
  image: docker:19.03.12-dind
  stage: deploy
  before_script:
    - docker logout
    - docker login -u skillgroup28 -p 5544676hen
  script:
    - docker build -t skillgroup28/server .
    - echo "Deploying application..."
    - docker push skillgroup28/server
    - echo "Application successfully deployed."
  artifacts:
    paths:
      - impl/target/impl-0.0.1-SNAPSHOT.jar
  tags:
    - push
